baseURL = "https://pingprogramadoras.org/"
languageCode = "es-es"
title = "Ping a Programadoras"
theme = "ananke"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 3 
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Nuestra comunidad nació el 16 de noviembre de 2016 en un encuentro en Sevilla organizado por dos feministas que querían romper con la brecha de género en la tecnología. Desde entonces hemos ido organizando eventos de diversa naturaleza: la proyección de documentales relacionados, talleres de introducción a tecnologías, talleres más avanzados y nuestros ya legendarios femiciclos."
  facebook = ""
  twitter = "https://twitter.com/pingmujeres"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image =  '/uploads/2020/01/IMG_5551-e1572258307276.jpg'
  recent_posts_number = 3
